// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfnETmvsn0RTNtVS38ypE2DmmBVBx0E6E',
    appId: '1:610574806316:android:8501ea36deacdb4077d089',
    messagingSenderId: '610574806316',
    projectId: 'pricebook-eef85',
    storageBucket: 'pricebook-eef85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDogQnjZQPQBFWwoemnAFEMa7aY9UDuvjc',
    appId: '1:610574806316:ios:99eff9b07713470d77d089',
    messagingSenderId: '610574806316',
    projectId: 'pricebook-eef85',
    storageBucket: 'pricebook-eef85.firebasestorage.app',
    iosBundleId: 'com.example.priceBook',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnuy-87PwMKW-94OgNdR-BonDE2zz_3Tw',
    appId: '1:610574806316:web:726173f8b44fc28e77d089',
    messagingSenderId: '610574806316',
    projectId: 'pricebook-eef85',
    authDomain: 'pricebook-eef85.firebaseapp.com',
    storageBucket: 'pricebook-eef85.firebasestorage.app',
    measurementId: 'G-0CX9WJ8SBH',
  );

}